### ISSUE TITLE
Using global CDNs make it unusable on offline on-prem TFS servers

### ISSUE THREAD

**Issue by evakili** [ALM-Rangers/Countdown-Widget-Extension#1]
This project loads `jquery` from an online CDN, thus could not be used on servers that are not connected to the Internet.

**Comment by michha** [comment]
In _countdown.html_ and _countdownconfiguration.html_ jquery is loaded from code.jquery.com in version 1.11.1 but there is also a local _jquery.js_ in _scripts/lib_ but thats version 3.1.0 . So maybe everything to solve the issue
If I would know how to test code changes for this extension, I could try to make a pull request.

**Comment by WouterDeKort** [comment]
Hi @michha, you can test the extension by compiling the code locally and then using the NPM scripts in the package.json file to package the extension. You can then install this extension locally in your own account with your own publisher and test it. This is documented at https://www.visualstudio.com/en-us/docs/integrate/extensions/publish/overview.

A pull request would be very welcome!

**Comment by WouterDeKort** [comment]
@evakili, I've been working on updating the Countdown Widget and I've also fixed this issue. Can you please try the newest version and see if it fixes your issue and now works on your disconnected servers?

**Comment by markvandenberg** [comment]
@WouterDeKort, Where can I find the latest resolving this issue? I have the same problem and like to test it.

**Comment by evakili** [comment]
@WouterDeKort Did you ask me to build it from Github repo? There are no updates on VS marketplace.

**Comment by wpschaub** [comment]
@markvandenberg @evakili  we're busy validating the latest version and will publish to marketplace shortly.
