### ISSUE TITLE
More colors.

### ISSUE THREAD

**Issue by pacovidal** [ALM-Rangers/Countdown-Widget-Extension#17]
Thanks for the widget. Would it be possible to have more colors available? the choice is quite limited at the moment.

**Comment by WouterDeKort** [comment]
Hi @pacovidal,

thanks for the suggestion. We are currently using a plugin called spectrum-colorpicker for the color picker. I'll look into the settings of this plugin if we can easily enable more colors or that we need to switch to another plugin.

I'll update this issue when I know more.

Thanks,
Wouter
