### ISSUE TITLE
Conditional formatting.

### ISSUE THREAD

**Issue by pacovidal** [ALM-Rangers/Countdown-Widget-Extension#18]
Would it be possible to support conditional formatting in this widget, depending on the number of days left? Thanks.

**Comment by WouterDeKort** [comment]
Thanks for your suggestion! I'm currently working on the backlog for the next version of the Countdown Widget and conditional formatting sounds like a great feature.

Can you tell me more about what it is you would like to see? I imagine something like changing the background color of the widget as the end date comes closer? Anything else you would like to see?

**Comment by pacovidal** [comment]
Hi - thanks for reaching out. Yes, the example would be a widget that goes
from green to yellow, orange and finally red as the a date looms closer.

Cheers,
Paco
