### ISSUE TITLE
Days are showing as partial

### ISSUE THREAD

**Issue by EdPerminas** [ALM-Rangers/Countdown-Widget-Extension#27]
Hello,

Countdown widget now shows remaining days as partial: 32.6, 97.6, etc..

Is there a setting where it could round up days?

Thank you

**Comment by wpschaub** [comment]
We're thinking about making it a configurable option in future releases. Happy to accept a pull request if it's urgent.

**Comment by EdPerminas** [comment]
Hello,

I don't think if it is that urgent, I'm curious why widget started to show partial days, when earlier it always showed as rounded days?

Thanks!
Ed

**Comment by wpschaub** [comment]
It's been the oldest and most asked for feature request. As mentioned above we're looking into making it configurable and the team is also looking at other ways of presenting the count down widgets.

Teams running across different time zones often questions the data shown. With fractions it's hopefully going to be a bit more verbose. However, we understand that for some the fraction is noise.

**Comment by FabienLavocat** [comment]
I've created a pull request to address this issue. In our dashboard we don't really like having non rounded number, it's not a very useful information to us.
