### ISSUE TITLE
Extension "support" link doesn't provide help/support for this extension

### ISSUE THREAD

**Issue by willsmythe** [ALM-Rangers/Countdown-Widget-Extension#44]
Currently, the "Support" link for this extension on the VS Marketplace redirects users to: https://blogs.msdn.microsoft.com/visualstudioalmrangers/. This is not a very useful place for getting help/support for this extension.

You should consider updating it to point to GitHub issues instead (https://github.com/ALM-Rangers/Countdown-Widget-Extension/issues)

**Comment by henrybeen** [comment]
I concur, the link in the manifest is (I believe) an old redirect. I've added an extra PR to go through with the other changes as soon as they go through
