### ISSUE TITLE
The Countdown widget doesnt show the right amount of days left

### ISSUE THREAD

**Issue by fredericocarneiro** [ALM-Rangers/Countdown-Widget-Extension#56]
Hi

I´m facing a problem during using the CountDown widget.

I´ve setted it to coutdown the days from today(Nov 30 to Dec 7).

If I check the "Skip non-working days" option, the count shows 2.5 days which is wrong because the right value should be 4.5 or 5.

If I doesnt check the "Skip non-working days" option, the count show 6.5 days, which is right because its counting the weekend.

**Comment by henrybeen** [comment]
Unfortunately the fix has been delayed, but it is now available. We are releasing this fix in a new version of the widgets, that are released using a new publisher. Could you please install this new extension and see if that fixes your issue?

![afbeelding](https://user-images.githubusercontent.com/19696205/52918159-6803cf80-32f4-11e9-93c0-82edad30242f.png)


Henry

**Comment by henrybeen** [comment]
@fredericocarneiro I was wondering, have you maybe given the above a try?

**Comment by henrybeen** [comment]
Closed due to no more response
