### ISSUE TITLE
Why is this extension a duplicate?

### ISSUE THREAD

**Issue by Christ0phH** [ALM-Rangers/Countdown-Widget-Extension#58]
Do you guys have a good explanation why we now have a duplicate of [Countdown Widget | 
Microsoft DevLabs](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.CountdownWidget ) which has 8000 installs already?

**Comment by WouterDeKort** [comment]
Unfortunately we had to move to another publisher. This is because we no longer have full control of the original publisher since the person who created that account has left Microsoft.

We know this is not a pretty solution and we thought long and hard but now that we have a new publisher that we can fully control we can move forward again.

**Comment by Christ0phH** [comment]
> Unfortunately we had to move to another publisher. This is because we no longer have full control of the original publisher since the person who created that account has left Microsoft.
> 
> We know this is not a pretty solution and we thought long and hard but now that we have a new publisher that we can fully control we can move forward again.

Honestly, that made me laugh, but that situation happend to a former employer of mine too.  I assume this circumstance affects all "DevLabs" Extension then? That would answer why the open issues within the feature timeline ( we wanted to roll out that extension to our 5000+ enterprise, but not when its not working with the FireFox ESL ...) 

I hope you will find a place to inform others about the situation or did you already?

**Comment by henrybeen** [comment]
It is a difficult situation indeed. The new widget is now shipped and under test by a number of users. When there are no issues, the old widget will be delisted and we will ask for ratings, counts, etc. to be moved.

More info is also available at https://www.almdevopsrangers.org/moving-our-extensions-to-a-new-publisher/

**Comment by Christ0phH** [comment]
Hi guys and thanks for the quick responses. 

May i ask how i as representative of my company (Bosch Rexroth) could contact you (alm rangers) regarding one of the other 'devlabs extensions' -> [Feature Timeline wont load in Firefox 60.X.XX ESR](https://github.com/Microsoft/featuretimeline/issues/79)

**Comment by WouterDeKort** [comment]
I don't think that one is from the ALM Rangers... I'm afraid that's one from Microsoft themselves who use the devlabs publisher for experimental extensions. I can see that the committers on that repository all say on their profile they work for Microsoft. I'll send an email to the Product Group and ask them to look at it.

**Comment by Christ0phH** [comment]
Thanks @WouterDeKort  Finals question, is there a public communication channel for the rangers group?

**Comment by WouterDeKort** [comment]
The link Henry posted points to our new blog. That's what we're going to use in the future.
