### ISSUE TITLE
Sprint countdown off by a day

### ISSUE THREAD

**Issue by jdshkolnik** [ALM-Rangers/Countdown-Widget-Extension#8]
Today is Thursday 10/20 and my sprint ends on Tuesday 10/25. The countdown widget shows 2 days remaining if we skip days off and 4 days remaining if we don't skip. By my count, it should be 3 days (Friday, Monday, Tuesday) or 5 days (Friday, Saturday, Sunday, Monday, Tuesday) if we don't count today.

![image](https://cloud.githubusercontent.com/assets/2047520/19562190/661a2f6e-96a9-11e6-8dcd-f042a147626f.png)

**Comment by wpschaub** [comment]
Team included a a fix in Fix Bug 12642 : countdown sprint missing 1 day (PR [#11](https://github.com/ALM-Rangers/Countdown-Widget-Extension/pull/11)). Please evaluate code changes and re-test with version 1.2.45 (or higher) from the ([marketplace](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.CountdownWidget)).

**Comment by jdshkolnik** [comment]
Looks good, thanks.
